# Dockerfile for Express server
FROM node:18

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# # Expose the port the API runs on
# EXPOSE 3001

# Start the API server
CMD ["npm","run", "server"]
